openapi: 3.1.0
info:
  title: OneEdge Automations API
  version: 1.0.0
  description: Automation management and credential storage endpoints

servers:
  - url: /api/v1

paths:
  /automations/templates:
    get:
      operationId: listAutomationTemplates
      summary: List automation templates
      tags: [Templates]
      parameters:
        - name: category
          in: query
          schema:
            type: string
            enum: [gsuite, slack, jira, chat, custom]
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutomationTemplate'

  /automations/templates/{id}:
    get:
      operationId: getAutomationTemplate
      summary: Get template details
      tags: [Templates]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Template details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomationTemplate'

  /automations:
    get:
      operationId: listAutomations
      summary: List user's automations
      tags: [Automations]
      parameters:
        - name: is_active
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: List of automations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Automation'

    post:
      operationId: createAutomation
      summary: Create an automation
      tags: [Automations]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutomationCreate'
      responses:
        '201':
          description: Automation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Automation'

  /automations/{id}:
    get:
      operationId: getAutomation
      summary: Get automation details
      tags: [Automations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Automation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Automation'

    patch:
      operationId: updateAutomation
      summary: Update an automation
      tags: [Automations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutomationUpdate'
      responses:
        '200':
          description: Automation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Automation'

    delete:
      operationId: deleteAutomation
      summary: Delete an automation
      tags: [Automations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Automation deleted

  /automations/{id}/execute:
    post:
      operationId: executeAutomation
      summary: Manually trigger automation
      tags: [Automations]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trigger_data:
                  type: object
                  description: Optional data to pass to trigger
      responses:
        '200':
          description: Execution started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomationExecution'

  /automations/{id}/executions:
    get:
      operationId: listExecutions
      summary: List automation executions
      tags: [Executions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, running, success, failed]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of executions
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AutomationExecution'
                  total:
                    type: integer

  /credentials:
    get:
      operationId: listCredentials
      summary: List EdgeVault credentials
      tags: [Credentials]
      parameters:
        - name: integration_type
          in: query
          schema:
            type: string
            enum: [google, slack, jira, n8n, custom]
      responses:
        '200':
          description: List of credentials (without sensitive data)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credential'

    post:
      operationId: createCredential
      summary: Store a new credential
      tags: [Credentials]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialCreate'
      responses:
        '201':
          description: Credential stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'

  /credentials/{id}:
    get:
      operationId: getCredential
      summary: Get credential details (without sensitive data)
      tags: [Credentials]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Credential details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'

    patch:
      operationId: updateCredential
      summary: Update a credential
      tags: [Credentials]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialUpdate'
      responses:
        '200':
          description: Credential updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'

    delete:
      operationId: deleteCredential
      summary: Delete a credential
      tags: [Credentials]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Credential deleted

  /credentials/{id}/validate:
    post:
      operationId: validateCredential
      summary: Test credential validity
      tags: [Credentials]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  error:
                    type: string
                  validated_at:
                    type: string
                    format: date-time

  /ai-gallery/requests:
    get:
      operationId: listGalleryRequests
      summary: List user's AI gallery requests
      tags: [AI Gallery]
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, approved, rejected]
        - name: type
          in: query
          schema:
            type: string
            enum: [model, tool]
      responses:
        '200':
          description: List of requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AIGalleryRequest'

    post:
      operationId: createGalleryRequest
      summary: Submit a model/tool request
      tags: [AI Gallery]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIGalleryRequestCreate'
      responses:
        '201':
          description: Request submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIGalleryRequest'

  /ai-gallery/requests/{id}:
    get:
      operationId: getGalleryRequest
      summary: Get request details
      tags: [AI Gallery]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Request details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIGalleryRequest'

components:
  schemas:
    AutomationTemplate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        category:
          type: string
          enum: [gsuite, slack, jira, chat, custom]
        template_data:
          $ref: '#/components/schemas/AutomationDefinition'
        required_credentials:
          type: array
          items:
            type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time

    AutomationDefinition:
      type: object
      properties:
        trigger:
          $ref: '#/components/schemas/TriggerConfig'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/ActionConfig'
        model:
          type: string

    TriggerConfig:
      type: object
      properties:
        type:
          type: string
          enum: [schedule, webhook, email, event]
        config:
          type: object

    ActionConfig:
      type: object
      properties:
        type:
          type: string
          enum: [ai_process, send_email, post_message, create_doc, webhook]
        config:
          type: object

    Automation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        template_id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        config:
          $ref: '#/components/schemas/AutomationDefinition'
        is_active:
          type: boolean
        last_run_at:
          type: string
          format: date-time
        run_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AutomationCreate:
      type: object
      required:
        - name
        - config
      properties:
        template_id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        description:
          type: string
        config:
          $ref: '#/components/schemas/AutomationDefinition'
        is_active:
          type: boolean
          default: false

    AutomationUpdate:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
        config:
          $ref: '#/components/schemas/AutomationDefinition'
        is_active:
          type: boolean

    AutomationExecution:
      type: object
      properties:
        id:
          type: string
          format: uuid
        automation_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, running, success, failed]
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        duration_ms:
          type: integer
        trigger_data:
          type: object
        result_data:
          type: object
        error_message:
          type: string
        tokens_used:
          type: integer
        cost:
          type: number

    Credential:
      type: object
      properties:
        id:
          type: string
          format: uuid
        integration_type:
          type: string
          enum: [google, slack, jira, n8n, custom]
        label:
          type: string
        status:
          type: string
          enum: [active, expired, error]
        last_validated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CredentialCreate:
      type: object
      required:
        - integration_type
        - label
        - credentials
      properties:
        integration_type:
          type: string
          enum: [google, slack, jira, n8n, custom]
        label:
          type: string
          maxLength: 100
        credentials:
          type: object
          description: Integration-specific credentials (will be encrypted)

    CredentialUpdate:
      type: object
      properties:
        label:
          type: string
          maxLength: 100
        credentials:
          type: object
          description: New credentials (will be encrypted)

    AIGalleryRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        request_type:
          type: string
          enum: [model, tool]
        name:
          type: string
        description:
          type: string
        justification:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected]
        admin_notes:
          type: string
        reviewed_by:
          type: string
          format: uuid
        reviewed_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    AIGalleryRequestCreate:
      type: object
      required:
        - request_type
        - name
        - description
      properties:
        request_type:
          type: string
          enum: [model, tool]
        name:
          type: string
          maxLength: 100
        description:
          type: string
          minLength: 10
          maxLength: 2000
        justification:
          type: string
          maxLength: 2000

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
